### ISSUE TITLE
Validation error message

### ISSUE THREAD

**Issue by mdkssb** [PANTHEONtech/lighty-yang-validator#279]
**Question**
I'm trying to use lyv for yang models of a CISCO ISR 4K router. while using vesrion 20.2.0 of lyv, I'm getting the same error for all yang models. I'm not able to understand the origin of the error.
Here the use command and the output : 
$  ./lyv  -a router_schema/ -p router_schema/ 
name : cisco-xe-ietf-ipv4-unicast-routing-deviation@2015-09-11.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : Cisco-IOS-XE-event-history-types@2022-11-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : Cisco-IOS-XE-linecard-oper@2022-11-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : cisco-xe-openconfig-rib-bgp-ext@2016-11-30.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : CISCO-ENTITY-QFP-MIB@2014-06-18.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : Cisco-IOS-XE-device-tracking@2023-07-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : openconfig-pim@2021-04-21.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : common-mpls-static@2019-07-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : CISCO-OSPF-TRAP-MIB@2003-07-18.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : Cisco-IOS-XE-policy@2023-03-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : Cisco-IOS-XE-trace-events@2022-11-01.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}

name : INT-SERV-MIB@1997-10-03.yang, message: Failed to assemble Effective Model Context
extraneous input '}' expecting {<EOF>, SEP}
......

Do you have any idea about the resean I'm having this error ?
Thanks

**Comment by ihrasko** [comment]
Hello,

```
java -jar ./lyv.jar -a /home/odl/projects/github/yang/vendor/cisco/xe/17141 -p /home/odl/projects/github/yang/vendor/cisco/xe/17141 -f tree | tee /home/odl/Desktop/cisco-xe.tree
```

with models from https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/17141 work just fine.

Enjoy!

**Comment by ihrasko** [comment]
The error means that you are missing `{` somewhere in your models.
