### ISSUE TITLE
Node name collision

### ISSUE THREAD

**Issue by mikemabonzo** [PANTHEONtech/lighty-yang-validator#77]
**Describe the bug**
using lyv on an ericsson-epg yang model which passes validation using pyang is failing on lyv with the following error:
 [digitata@server106 ~]$ lighty-yang-validator-16.1.0/lighty-yang-validator-16.1.0/lyv pcc_yang/ericsson-epg.yang
Exception in LYV application: Error in module 'ericsson-epg': cannot add '(urn:rdns:com:ericsson:oammodel:ericsson-epg?revision=2022-01-26)priority'. Node name collision: '(urn:rdns:com:ericsson:oammodel:ericsson-epg?revision=2022-01-26)priority' already declared at pcc_yang/ericsson-epg.yang:5008:29 [at pcc_yang/ericsson-epg.yang:5008:29]
**Branch**
LYV branch 16.1.0

**To Reproduce**
see Describe Bug above.

**Expected behavior**
Correct handling of name: priority in the yang model is needed. The above error does not appear in version 13.2.0.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [uname -a] Linux server106 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version [java -version] java version "17.0.1" 2021-10-19 LTS
 - Maven version [mvn -version] Apache Maven 3.8.6

**Additional context**

Thank you for creating your report! We will get back to you, as soon as possible. Please note, that our support on GitHub is based on a non-guaranteed best effort. As soon as we are able, we will get back to you.
 
If you are in a hurry and have an inquiry regarding commercial support, please via this contact form: https://pantheon.tech/contact-us

**Comment by ihrasko** [comment]
Thank you for your interest. We are investigating the issue.

**Comment by ihrasko** [comment]
Seems to be related to: https://jira.opendaylight.org/browse/YANGTOOLS-1445

**Comment by ihrasko** [comment]
Fixed in lighty.io YANG validator version 17.0.1.
Enjoy!
